version: '3'

services:
        firekylin:
                container_name: firekylin_app
                build: 
                        context: ./firekylin
                        dockerfile: Dockerfile
                restart: always
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                ports:
                        - 8001:8360
                depends_on:
                        - mysql
        mysql:
                image: 'mysql:5.7'
                restart: always
                container_name: mysql
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                        - ./mysql/data/:/var/lib/mysql/
                environment:
                        MYSQL_ROOT_PASSWORD : "123456"
                        MYSQL_DATABASE : "firekylin"
                        MYSQL_USER : "blog"
                        MYSQL_PASSWORD : "123456"
                expose:
                        - "3306"
        isso:
                image: wonderfall/isso
                environment:
                        - GID=1000
                        - UID=1000
                volumes:
                        - ./isso/config:/config
                        - ./isso/db:/db
                ports:
                        - "8002:8080"
