version: '3'

services:
        nginx:
                image: evild/alpine-nginx
                restart: always
                container_name: nginx
                volumes:
                        - ./nginx/nginx.conf:/etc/nginx/conf/nginx.conf:ro
                        - ./nginx/logs/:/var/log/nginx/
                ports:
                        - 80:80
                depends_on:
                        - firekylin
                        - isso
        firekylin:
                container_name: firekylin_app
                image: firekylin/firekylin
                restart: always
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                        - ./firekylin/web/db.js:/var/lib/firekylin/db.js
                        - ./firekylin/web/upload/:/var/lib/firekylin/upload/
                expose:
                        - 8360
                depends_on:
                        - mysql
        mysql:
                image: 'mysql:5.7'
                restart: always
                container_name: mysql
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                        - ./mysql/data/:/var/lib/mysql/
                environment:
                        MYSQL_ROOT_PASSWORD : "123456"
                        MYSQL_DATABASE : "firekylin"
                        MYSQL_USER : "blog"
                        MYSQL_PASSWORD : "123456"
                expose:
                        - "3306"
        isso:
                image: wonderfall/isso
                environment:
                        - GID=1000
                        - UID=1000
                volumes:
                        - ./isso/config:/config
                        - ./isso/db:/db
                expose:
                        - 8080
